2024-07-06 23:23:36,253 INFO    MainThread:79507 [wandb_setup.py:_flush():76] Current SDK version is 0.17.3
2024-07-06 23:23:36,254 INFO    MainThread:79507 [wandb_setup.py:_flush():76] Configure stats pid to 79507
2024-07-06 23:23:36,254 INFO    MainThread:79507 [wandb_setup.py:_flush():76] Loading settings from /home/arsalan/.config/wandb/settings
2024-07-06 23:23:36,254 INFO    MainThread:79507 [wandb_setup.py:_flush():76] Loading settings from /home/arsalan/DATA/github_files/keras_cv/TyreQualityPrediction/notebooks/wandb/settings
2024-07-06 23:23:36,254 INFO    MainThread:79507 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-06 23:23:36,254 INFO    MainThread:79507 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-06 23:23:36,254 INFO    MainThread:79507 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-07-06 23:23:36,254 INFO    MainThread:79507 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-06 23:23:36,254 INFO    MainThread:79507 [wandb_init.py:_log_setup():520] Logging user logs to /home/arsalan/DATA/github_files/keras_cv/TyreQualityPrediction/notebooks/wandb/run-20240706_232336-30qtlwk3/logs/debug.log
2024-07-06 23:23:36,254 INFO    MainThread:79507 [wandb_init.py:_log_setup():521] Logging internal logs to /home/arsalan/DATA/github_files/keras_cv/TyreQualityPrediction/notebooks/wandb/run-20240706_232336-30qtlwk3/logs/debug-internal.log
2024-07-06 23:23:36,255 INFO    MainThread:79507 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7530280462d0>
2024-07-06 23:23:36,255 INFO    MainThread:79507 [wandb_init.py:init():560] calling init triggers
2024-07-06 23:23:36,255 INFO    MainThread:79507 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-07-06 23:23:36,255 INFO    MainThread:79507 [wandb_init.py:init():610] starting backend
2024-07-06 23:23:36,255 INFO    MainThread:79507 [wandb_init.py:init():614] setting up manager
2024-07-06 23:23:36,262 INFO    MainThread:79507 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-07-06 23:23:36,263 INFO    MainThread:79507 [wandb_init.py:init():622] backend started and connected
2024-07-06 23:23:36,286 INFO    MainThread:79507 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-07-06 23:23:36,305 INFO    MainThread:79507 [wandb_init.py:init():711] updated telemetry
2024-07-06 23:23:36,316 INFO    MainThread:79507 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-07-06 23:25:06,380 ERROR   MainThread:79507 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-07-06 23:25:06,380 ERROR   MainThread:79507 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/home/arsalan/miniconda3/envs/tfgpu_2.16/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/arsalan/miniconda3/envs/tfgpu_2.16/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
